### PR TITLE
refactor: slicing ui using without antd

### PR DESCRIPTION
**Pull request by bimogempar**
cause i think antd cant use flexiibility for customization, so i decide back to use tailwind and can increase speed of slicing and i'll install dependecies2 which needed for tailwind

changes:
- remove antd
- install tailwind, react-tailwind-datepicker, dayjs
- conf setup tailwind for react vite

status:
- done create layout user (not admin)
- done create landing page

note:
- mas @ZulfanFaizal11 nanti tolong branch staging dibuatkan preview nya di vercel, feel free buat set meet/dc buat setup nya

### CODE REVIEW

**Comment by bimogempar** [comment]
udah tk bantu buat merge conflict nya ya mas mas, minta bantuan check lagi aja thankssssss 

@RizkiB12 @ZulfanFaizal11

**Comment by RizkiB12** [comment]
Berarti jadi tailwind ya sekarang dari user sama adminnya ?

**Comment by bimogempar** [comment]
sementara yess

**Comment by RizkiB12** [comment]
enak pake antd kayaknya, tapi gakpapa boleh dicoba

**Comment by bimogempar** [comment]
yes broo sementara @RizkiB12

**Comment by RizkiB12** [comment]
okeee push en sek gakpopo, tak coba lanjut antd

**Comment by bimogempar** [comment]
mntabbb coolll

**Pull request merged**
